### PR TITLE
Feature/home nav data

### PR DESCRIPTION
**Pull request by surajmore98**
added:

- Navbar component
- Home Page
- Image and Data for video and categories

### CODE REVIEW

**Review by ravikumar1002 — APPROVED** [review]
Clean code 
Good naming conventions
good to merge

**Review by samyakshah3008 — APPROVED** [review]
Clean code and UI 
Good naming conventions
Looks good for approval

**Comment by samyakshah3008** [comment]
You can add all images from online youtube thumbnail getter and keep your images as on cloud instead of local machine

**Comment by surajmore98** [comment]
> You can add all images from online youtube thumbnail getter and keep your images as on cloud instead of local machine

Thanks for suggestion, I will look in to this

**Pull request merged**
